routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('tasks', 'TasksController');
Route::delete('/trash/{task}', 'TasksController@trash')->name('tasks.trash');
Route::get('/trashed', 'TasksController@trashed')->name('tasks.trashed');
Route::put('/restore/{task}', 'TasksController@restore')->name('tasks.restore');
Route::post('tasks/{task}/completed', 'StatusController@update')->name('tasks.completed');
Route::post('tasks/{task}/incomplete', 'StatusController@updateIncomplete')->name('tasks.incomplete');
// Route::get('tasks/{slug}', 'TasksController@show')->name('tasks.show');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Task extends Model
{
    use SoftDeletes;
    use HasFactory;
    protected $dates = ['deadline', 'updated_at', 'created_at'];
    protected $appends = ['diffInDays'];
    protected $fillable = [
        'title', 'body', 'user_id', 'slug', 'deadline', 'status', 'leader_id'
    ];
    public function getDiffInDaysAttribute()
    {
        return $this->deadline->diffInDays($this->updated_at);
    }
    public function setTitleAttribute($title){
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }
    
    public function getUrlAttribute(){
        return "tasks/{$this->slug}";
    }

    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }


    public function status(){
        return $this->belongsTo(Task::class);
    }

    public function member(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function leader(){
        return $this->belongsTo(User::class, 'leader_id');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Tasks\CreateTaskRequest;
use App\Http\Requests\Tasks\UpdateTaskRequest;

use Illuminate\Support\Str;

use App\Task;
use App\User;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        $this->middleware(['auth'])->only(['create', 'store', 'edit', 'update', 'index']);
    }

    public function index()
    {
        // if(Gate::allows('show-task', $task)) {
            $users = User::all();
            $tasks = Task::all();
            $flag = false;
            $statusFlag = false;
            return view('tasks.index', compact([
            'statusFlag',
            'flag',
            'users',
            'tasks'
        ]));
        // }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // if(auth()->user()->can('add-task', $task)) {
            $users = User::all();
            $tasks = Task::all();
            return view('tasks.create', compact([
                'users',
                'tasks'
        ]));
        // }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $slug = $request->title;
        $task = Task::create([
            'title'=>$request->title,
            'slug' => Str::slug($slug),
            'body'=>$request->body,
            'user_id'=>$request->users,
            'leader_id' => auth()->user()->id,
            'deadline'=>$request->deadline
        ]);

        // dd($request);
        // dd($request->tags);

        session()->flash('success', 'Task Created Successfully');
        
        return redirect(route('tasks.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        return view('tasks.show', compact([
            'task'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        $users = User::all();
        return view('tasks.edit', compact([
            'users',
            'task'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $data= $request->only(['title', 'body', 'user_id', 'deadline']);
        // dd($data);
        $task->update($data);


        session()->flash('success', 'Task Updated Successfully');
        
        return redirect(route('tasks.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::onlyTrashed()->findOrFail($id);
        $task->forceDelete();
        session()->flash('success', 'Task Deleted Successfully');
        return redirect()->back();

    }

    public function trash(Task $task)
    {
        $task->delete();
        session()->flash('success', 'Task Trashed Successfully');
        return redirect(route('tasks.index'));
    }

    public function trashed()
    {
        // $trashed = DB::table('tasks')->whereNotNull('deleted_at');
        $trashed = Task::onlyTrashed()->paginate(1);
        return view('tasks.trashed')->with('tasks', $trashed);
    }

    public function restore($id){
        $trashedTask = Task::onlyTrashed()->findOrFail($id);
        $trashedTask->restore();
        session()->flash('success', 'Task restored Successfully');
        return redirect(route('tasks.index'));    
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card text-center">
    <div class="card-header">
        <h3 class="mt-2">Add Task</h3>
    </div>
    <div class="card-body">
    <form action="{{ route('tasks.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <div class="row">
                <div class="col-md-2 mt-1">
                <label for="title"><h3>Title</h3></label>
                </div>
                <div class="col-md-10">
                <input type="text"
                value="{{ old('title') }}"
                class="form-control @error('title') is-invalid @enderror"
                name="title" id="title">
                @error('title')
                    <p class="text-danger">{{ $message }}</p>
                @enderror
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                    <div class="col-md-2 mt-1">
                        <label for="body"><h3>Body</h3></label>
                    </div>
                    <div class="col-md-10">
                        <input type="text"
                        value="{{ old('body') }}"
                        class="form-control @error('body') is-invalid @enderror"
                        name="body" id="body">
                        @error('body')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-md-2 mt-4">
                    <label for="users"><h3>Members</h3></label>
                </div>
                <div class="col-md-10">
                    <select name="users" id="users" class="form-control select2">
                    @foreach($users as $user)
                    @if($user->role === 'member')
                        <option value="{{$user->id}}">{{$user->name}}
                        </option>
                    @endif
                        @endforeach
                        </select>
                    @error('user')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-md-2 mt-1">
                    <label for="deadline"><h3>Deadline</h3></label>
                </div>
                <div class="col-md-10">
                    <input type="date"
                    value="{{ old('deadline') }}"
                    class="form-control @error('deadline') is-invalid @enderror"
                    name="deadline" id="deadline">
                    @error('deadline')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-success" type="submit">Add Task</button>
        </div>
    </form>
    </div>
</div>

@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
        <div class="card-header">
            Edit Task
        </div>

        <div class="card-body">
            <form action="{{ route('tasks.update', $task) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                    value="{{ old('title', $task->title) }}"
                    class="form-control @error('title') is-invalid @enderror"
                    name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="excerpt">Body</label>
                    <textarea
                    class="form-control @error('body') is-invalid @enderror"
                    name="body" id="body" rows="4">{{ old('body', $task->body) }}</textarea>
                    @error('body')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Members</label>
                    <select name="user_id" id="user_id" class="form-control select2">
                    @foreach($users as $user)
                    @if($user->role === 'member')
                        <option value="{{old('user_id', $user->id)}}">{{$user->name}}
                        </option>
                    @endif
                        @endforeach
                        </select>
                    @error('user_id')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="deadline">Deadline</label>
                    <input type="date"
                    value="{{ old('deadline', $task->deadline)}}"
                    class="form-control @error('deadline') is-invalid @enderror"
                    name="deadline" id="deadline">
                    @error('deadline')
                        <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Update Task</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
@endsection

@section('content')
<div class="row">
    @foreach($users as $user)
        @if($user->tasks->count() > 0 && auth()->user()->role === 'leader' && $user->role != auth()->user()->role )
        <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <div class="row mt-2">
                    <div class="col-md-12 text-center">
                        <h5>
                        @foreach($user->tasks as $userTask)
                        @if($user->is_completed_value($userTask,$userTask->member->id) === $user->tasks->count())
                        <?php $statusFlag = true; ?>
                        @endif
                        @endforeach
                        @if($statusFlag)
                            <i class="fa fa-check"></i>
                        @endif
                        {{$user->name}}
                        </h5>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @foreach($tasks as $task)
                @if($user->table($task)->member->id === $user->id && ($user->table($task)->leader->id !== auth()->user()->id))
                <!-- <p>H</p> -->
                @endif
                    @if($user->name === $task->member->name && $task->leader_id === auth()->user()->id)
                    <div class="card-header mt-2">
                        <p>
                        @if($task->status === 'completed')
                            <i class="fa fa-check"></i>
                        @endif
                        <a href="{{route('tasks.show', $task)}}">{!! Str::limit($task->title, 25) !!}</a>
                        </p>
                    </div>
                    @endif
                @endforeach
            </div>
            <div class="card-header text-center">
                <a href="{{ route('tasks.create') }}">
                <i class="fa fa-plus"></i>
                Add Another task
                </a>
            </div>
        </div>
        </div>
        @endif
    @endforeach
    @foreach($users as $user)
    @if($user->tasks->count() > 0 && auth()->user()->role !== 'leader' && $user->id === auth()->user()->id)
        <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <div class="row mt-2">
                    <div class="col-md-12 text-center">
                        <h5>
                        @foreach($user->tasks as $userTask)
                            @if($user->is_completed($userTask) === $user->tasks->count() && $user->name === auth()->user()->name)
                                <?php $flag = true; ?>
                            @endif
                        @endforeach
                        @if($flag)
                        <i class="fa fa-check"></i>
                        @endif
                        {{auth()->user()->name}}
                        </h5>
                    </div>
                </div>
            </div>
            <div class="card-body">
                @foreach($tasks as $task)
                @if(auth()->user()->name === $task->member->name)
                <div class="card-header mt-2">
                    <p>
                    @if($task->status === 'completed')
                        <i class="fa fa-check"></i>
                    @endif
                    <a href="{{route('tasks.show', $task)}}">
                    {!! Str::limit($task->title, 25) !!}
                    </a>
                    </p>
                    </div>
                @endif
                @endforeach
            </div>
        </div>
        </div>
    @endif
    @endforeach
</div>

@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12"> 
            <div class="card">
                <div class="card-header">
                    <h3>{{$task->title}}</h3>
                </div>
                <div class="card-body">
                    <p>{{$task->body}}</p>
                    <p class="text-muted">Deadline: {!! Str::limit($task->deadline, 11) !!}</p>
                    <p class="text-muted">Assigned : {{$task->created_date}}</p>
                    <p class="text-muted">Task For : {{$task->member->name}}</p>
                    <p class="text-muted">Status : {{$task->status}}</p>
                    @if(auth()->user()->role === 'leader')
                        <a href="{{route('tasks.edit', $task)}}" class="btn btn-success">
                        <i class="fa fa-edit"></i>
                        Edit
                        </a>
                        <a href="" class="btn btn-danger" onclick="displayModalForm({{ $task }})"
                            data-toggle="modal" data-target="#deleteModal">
                        <i class="fa fa-trash"></i>
                        Trash
                        </a>
                        @if($task->status === 'resolving')
                        <form action="{{route('tasks.completed', $task)}}" method="POST" style="display: inline-block">
                        @csrf
                        <button type="submit" class="btn btn-primary">Resolve</button>
                        </form>
                        <form action="{{route('tasks.incomplete', $task)}}" method="POST" style="display: inline-block">
                        @csrf
                        <button type="submit" class="btn btn-primary">UnResolve</button>
                        </form>
                        @endif
                        <a href="{{route('tasks.trashed')}}" class="btn btn-danger" >
                        <i class="fa fa-trash"></i>
                        View Trashed Tasks
                        </a>
                        <a href="{{route('tasks.index')}}" class="btn btn-primary" >
                        View Tasks
                        </a>
                    @elseif(auth()->user()->role === 'member')
                        <p class="text-muted">Assigned By : {{$task->leader->name}}</p>
                        <form action="{{route('tasks.completed', $task)}}" method="POST" style="display:inline-block">
                        @csrf
                        @if($task->status === 'resolving')
                            <p style="color: green">Resolving...</p>
                        @elseif($task->status === 'completed')
                            <p style="color: green">Completed</p>
                        @elseif($task->status === 'incomplete')
                        <button type="submit" class="btn btn-outline-primary">Mark As Completed</button>
                        @endif
                    </form>
                    <a href="{{route('tasks.index')}}" class="btn btn-primary" >
                        View Tasks
                    </a>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                </div>
            <div class="modal-body">
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    <p>Are you sure you wanna trash?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn btn-danger">
                        Trash
                    </button>
                </div>
            </form>
            </div>
            </div>
    </div>

@endsection

@section('page-level-scripts')
    <script>
        function displayModalForm($task){
            var url = '/trash/'+$task.id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection

resources/views/tasks/trashed.blade.php
@extends('layouts.app')
@section('content')
    <div class="d-flex justify-content-end mb-3 mt-3">
        <a href="{{ route('tasks.create') }}" class="btn btn-primary">Add Tasks</a>
    </div>
    <div class="card">
        <div class="card-header">
            Tasks
        </div>
        <div class="card-body">
        @if($tasks->count() > 0)
            <table class="table table-bordered">
                <thead>
                    <th>Title</th>
                    <th>Body</th>
                    <th>Deadline</th>
                    <th>Assigned</th>
                    <th>Member</th>
                    <th>Action</th>
                </thead>
                <tbody>
                    @foreach($tasks as $task)
                    <tr>
                        <td>{{$task->title}}</td>
                        <td>{{$task->body}}</td>
                        <td>{!! Str::limit($task->deadline, 11) !!}</td>
                        <td>{{$task->created_date}}</td>
                        <td>{{$task->member->name}}</td>
                        <td>
                            <form action="{{route('tasks.restore', $task->id)}}" method="POST">
                                @csrf
                                @method('PUT')
                                <button class="btn btn-primary btn-sm" type="submit">Restore</button>
                            </form>
                            <a href="" class="btn btn-danger btn-sm"
                            onclick="displayModalForm({{$task}})"
                            data-toggle="modal"
                            data-target="#deleteModal">Delete</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            @else
                <h5>Nothing to delete</h5>
            @endif
        </div>
        <div class="card-footer">
            {{ $tasks->links() }}
        </div>
    </div>
    
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
                </div>
            <div class="modal-body">
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    <p>Are you sure you wanna delete</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        Close
                    </button>
                    <button type="submit" class="btn btn-danger">
                        Delete Task
                    </button>
                </div>
            </form>
            </div>
            </div>
    </div>
@endsection
@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($task){
            var url = '/tasks/'+$task.id;
            $("#deleteForm").attr('action', url);
        }
    </script>
@endsection